name: AdvancementBarrierPaper
version: '1.0'
main: dev.chsr.advancementBarrierPaper.AdvancementBarrierPaper
api-version: '1.21'
commands:
  nextTask:
    description: skip current task
  setTask:
    description: set task